name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/rehlds
  DOCKER_PLATFORMS: linux/amd64

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ env.DOCKER_PLATFORMS }}
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:latest
        