name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - '.github/workflows/dockerhub-description.yml'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mod: [
          { slug: valve,      tagName: legacy },
          { slug: valve,      tagName: bugfixedhl },

          { slug: cstrike,    tagName: legacy },
          { slug: cstrike,    tagName: regamedll },

          { slug: czero,      tagName: legacy },
          { slug: czero,      tagName: regamedll },

          { slug: dod,        tagName: legacy },
          { slug: gearbox,    tagName: legacy },
          { slug: tfc,        tagName: legacy },
          { slug: ricochet,   tagName: legacy },
          { slug: dmc,        tagName: legacy },
        ]
    env:
      needToPush: ${{ github.ref_name == github.event.repository.default_branch }}

    steps:
    - name: test env
      run: echo "github.ref_name:${{github.ref_name}}, github.event.repository.default_branch:${{github.event.repository.default_branch}}"

    - uses: actions/checkout@v4.1.1
    - uses: docker/setup-buildx-action@v3.2.0
    
    - name: Log in to Docker Hub
      if: ${{ env.needToPush }}
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      env:
        rehldsVersion: latest
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ env.needToPush }}
        tags: |
          ${{ vars.DOCKER_USERNAME }}/rehlds-${{ matrix.mod.slug }}:${{ matrix.mod.tagName }}
          ${{ matrix.mod.tagName == 'legacy' && format('{0}/rehlds-{1}:latest', vars.DOCKER_USERNAME, matrix.mod.slug) || null}}
        build-args: |
          MOD=${{ matrix.mod.slug }}
          ReHLDS_VERSION=${{ env.rehldsVersion }}
          ${{ matrix.mod.tagName != 'legacy' && 'ReGameDLL_VERSION=latest' || '' }}
          ${{ matrix.mod.tagName == 'legacy' && 'BugfixedHL_LINK=' || ''}}
        cache-from: type=gha,scope=build-${{ matrix.mod.slug }}-${{ matrix.mod.tagName }}
        cache-to: type=gha,mode=max,scope=build-${{ matrix.mod.slug }}-${{ matrix.mod.tagName }}