name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - '.github/workflows/dockerhub-description.yml'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mod:
          - valve
          - cstrike
          - czero
          - dod
          - gearbox
          - tfc
          - ricochet
          - dmc
        tagName:
          - legacy
          - regamedll
          - bugfixedhl
        exclude:
          - mod: valve
            tagName: regamedll
          - mod: cstrike
            tagName: bugfixedhl
          - mod: czero
            tagName: bugfixedhl
          - mod: dod
            tagName: [ bugfixedhl, regamedll ]

    env:
      needToPush: ${{ github.ref == 'refs/heads/master' }}

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: docker/setup-buildx-action@v3.2.0

    - name: Log in to Docker Hub
      if: ${{ env.needToPush }}
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      env:
        rehldsVersion: latest
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: false
        tags: |
          ${{ vars.DOCKER_USERNAME }}/rehlds-${{ matrix.mod }}:${{ matrix.tagName }}
        # ${{ matrix.tagName == 'legacy' && format('{0}/rehlds-{1}:latest', vars.DOCKER_USERNAME, matrix.mod) || null}}
        build-args: |
          MOD=${{ matrix.mod }}
          ReHLDS_VERSION=${{ env.rehldsVersion }}
          ${{ matrix.tagName != 'legacy' && 'ReGameDLL_VERSION=latest' || '' }}
          ${{ matrix.tagName == 'legacy' && 'BugfixedHL_LINK=' || ''}}
        cache-from: type=gha,scope=build-${{ matrix.mod }}-${{ matrix.tagName }}
        cache-to: type=gha,mode=max,scope=build-${{ matrix.mod }}-${{ matrix.tagName }}